// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: event/event.proto

package event

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QueryAPI_ListEventsByDistinctID_FullMethodName = "/QueryAPI/ListEventsByDistinctID"
	QueryAPI_EventCountOvertime_FullMethodName     = "/QueryAPI/EventCountOvertime"
)

// QueryAPIClient is the client API for QueryAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryAPIClient interface {
	ListEventsByDistinctID(ctx context.Context, in *ListEventsByDistinctIDRequest, opts ...grpc.CallOption) (*ListEventsByDistinctIDResponse, error)
	EventCountOvertime(ctx context.Context, in *EventCountOvertimeRequest, opts ...grpc.CallOption) (*EventCountOvertimeResponse, error)
}

type queryAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryAPIClient(cc grpc.ClientConnInterface) QueryAPIClient {
	return &queryAPIClient{cc}
}

func (c *queryAPIClient) ListEventsByDistinctID(ctx context.Context, in *ListEventsByDistinctIDRequest, opts ...grpc.CallOption) (*ListEventsByDistinctIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsByDistinctIDResponse)
	err := c.cc.Invoke(ctx, QueryAPI_ListEventsByDistinctID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryAPIClient) EventCountOvertime(ctx context.Context, in *EventCountOvertimeRequest, opts ...grpc.CallOption) (*EventCountOvertimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventCountOvertimeResponse)
	err := c.cc.Invoke(ctx, QueryAPI_EventCountOvertime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryAPIServer is the server API for QueryAPI service.
// All implementations must embed UnimplementedQueryAPIServer
// for forward compatibility.
type QueryAPIServer interface {
	ListEventsByDistinctID(context.Context, *ListEventsByDistinctIDRequest) (*ListEventsByDistinctIDResponse, error)
	EventCountOvertime(context.Context, *EventCountOvertimeRequest) (*EventCountOvertimeResponse, error)
	mustEmbedUnimplementedQueryAPIServer()
}

// UnimplementedQueryAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryAPIServer struct{}

func (UnimplementedQueryAPIServer) ListEventsByDistinctID(context.Context, *ListEventsByDistinctIDRequest) (*ListEventsByDistinctIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEventsByDistinctID not implemented")
}
func (UnimplementedQueryAPIServer) EventCountOvertime(context.Context, *EventCountOvertimeRequest) (*EventCountOvertimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EventCountOvertime not implemented")
}
func (UnimplementedQueryAPIServer) mustEmbedUnimplementedQueryAPIServer() {}
func (UnimplementedQueryAPIServer) testEmbeddedByValue()                  {}

// UnsafeQueryAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryAPIServer will
// result in compilation errors.
type UnsafeQueryAPIServer interface {
	mustEmbedUnimplementedQueryAPIServer()
}

func RegisterQueryAPIServer(s grpc.ServiceRegistrar, srv QueryAPIServer) {
	// If the following call pancis, it indicates UnimplementedQueryAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueryAPI_ServiceDesc, srv)
}

func _QueryAPI_ListEventsByDistinctID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsByDistinctIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryAPIServer).ListEventsByDistinctID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryAPI_ListEventsByDistinctID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryAPIServer).ListEventsByDistinctID(ctx, req.(*ListEventsByDistinctIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryAPI_EventCountOvertime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventCountOvertimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryAPIServer).EventCountOvertime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryAPI_EventCountOvertime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryAPIServer).EventCountOvertime(ctx, req.(*EventCountOvertimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueryAPI_ServiceDesc is the grpc.ServiceDesc for QueryAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "QueryAPI",
	HandlerType: (*QueryAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEventsByDistinctID",
			Handler:    _QueryAPI_ListEventsByDistinctID_Handler,
		},
		{
			MethodName: "EventCountOvertime",
			Handler:    _QueryAPI_EventCountOvertime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event/event.proto",
}
