name: Test Casssandratools

on:
  push:
    paths:
      - libraries/cassandratools/**
  pull_request:
    paths:
      - libraries/cassandratools/**

env:
  GO_VERSION: "1.22"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Run tests
        run: |
          go test -v -json ./... -cover
