FROM golang:1.22.9-alpine3.20 as development
WORKDIR /build
COPY . /build
RUN go build \
    -o api-server \
    ./cmd/api-server
RUN go install github.com/mitranim/gow@latest
ENTRYPOINT ["gow", "run", "./cmd/api-server"]

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=development /build/api-server /api-server

ENTRYPOINT ["/api-server"]
