FROM golang:1.22 AS development

WORKDIR /build
COPY . /build

RUN apt-get update && apt-get install -y \
    git \
    gcc \
    g++ \
    librdkafka-dev

RUN go build \
    -o api-server \
    ./cmd/api-server

FROM debian:12-slim

RUN apt-get update && apt-get install -y \
    librdkafka1 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt
COPY --from=development /build/api-server .

ENTRYPOINT ["./api-server"]