FROM golang:1.22 AS development

WORKDIR /build
COPY . /build

RUN apt-get update && apt-get install -y \
    git \
    gcc \
    g++ \
    librdkafka-dev

RUN CGO_ENABLED=1 GOOS=linux go build \
    -o api-server \
    ./cmd/api-server
RUN go install github.com/mitranim/gow@latest
ENTRYPOINT ["gow", "run", "./cmd/api-server"]

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=development /build/api-server /api-server

ENTRYPOINT ["/api-server"]
