FROM golang:1.22 AS development

WORKDIR /build
COPY . /build

RUN go build \
    -o eventquery \
    ./cmd/

FROM debian:12-slim

RUN apt-get update && apt-get install -y \
    librdkafka1 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt
COPY --from=development /build/eventquery /eventquery

ENTRYPOINT ["/eventquery"]