name: Test Casssandratools

on:
  push:
    paths:
      - libraries/cassandratools/**
      - .github/workflows/cassandratools.yaml
  pull_request:
    paths:
      - libraries/cassandratools/**
      - .github/workflows/cassandratools.yaml

env:
  GO_VERSION: "1.22"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libraries/cassandratools 
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Run tests
        run: |
          go test -v -json ./... -cover
